[package]
authors = ["Eduardo Lemos Rocha <dudulr10@gmail.com>"]
edition = "2021"
name = "rusting-images"
version = "0.1.0"

[dependencies]
image = "0.25.1"
clap = {version = "4.1.8", features = ["derive", "cargo"]}

